services:
  db:
    image: postgres:16.4
    volumes:
      - postgresql:/var/lib/postgresql/data:delegate
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  postgresql:
  storage:
