default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  port: 5432
  host: 127.0.0.1

development:
  <<: *default
  database: graph_menu_development

test:
  <<: *default
  database: graph_menu_test

production:
  <<: *default
  database: graph_menu_production
  username: graph_menu
  password: <%= ENV["GRAPH_MENU_DATABASE_PASSWORD"] %>
